AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda-custom-docker-sample

Globals:
  Function:
    Timeout: 3

Resources:
  MyCustomDocker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CustomDockerWithBash
      ImageUri: xxxxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/docker-lambda-bash:latest
      PackageType: Image
      Events:
        CustomDockerEcho:
          Type: Api
          Properties:
            Path: /echo
            Method: get

Outputs:
  MyCustomDockerApi:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/echo/'
